server:
  port: 8090
spring:
  application:
    name: MySpringBoot
  datasource:
    url: jdbc:postgresql://localhost:49153/postgres
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
file:
  path: count_default